
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://myznurmlxmpbgpsvovon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15em51cm1seG1wYmdwc3Zvdm9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzOTc3NTEsImV4cCI6MjA1OTk3Mzc1MX0.VKxOGzy_FMJntJo5sE4nE4I1BD7P5IgGCs8b3J2RpOE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
      storageKey: 'proval-auth-token',
      storage: localStorage
    }
  }
);
